### ISSUE TITLE
everytime code from app authenticator is wrong

### ISSUE THREAD

**Issue by urgido** [ekojs/ejsotp#1]
HI

I am using CI4 as framework and this library as Helper so, I loading it as the follow way:

// TOTP - 2FA
require_once(APPPATH.'Helpers/ejsotp/vendor/autoload.php');
use Ekojs\Otp\TOTP;

$ejsotp = TOTP::getInstance();
$ejsotp->createOTP(["secret" => $GetClienteInfo['2fa_secret']]);
$ejsotp->otp->setLabel($GetClienteInfo['email']);
$ejsotp->otp->setIssuer($tikeame_config['site_title']);
$ejsotp->generateQr();

The secret and qr code are created perfectly, I am able to scan the qr on my google app authenticator but the problem appears when I tried to validate a code. Everytime is false inclusive I did a test within the example of qr-code and secret given and the issue is the same.

IMPORTANT: Using the code generated by $ejsotp->otp->now() is working right when I tested a validation process!

NOTE: I am not using composer on my production server, I just install the library on my local machine and then I uploaded all files to the corresponding folder of CI 4.

PHP 8.1

Any fix for it?
Thanks

**Comment by ekojs** [comment]
hello @urgido , thanks for your issue. Can you double check the timezone and the time of your webserver ?
Because this problem may arise because of that.

if you provide more detail of your timezone, or ntp configuration of your environment in your framework, server or else may be i can help you out.
